openapi: 3.0.0
servers: []
info:
  description: KWCSSA Voting System 2022
  version: "1.1.0"
  title: KWCSSA Voting System
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: admin
    description: Secured Admin-only calls
  - name: voter
    description: Voter calls
paths:
  /vote/{round}/{id}:
    put:
      tags:
        - voter
      summary: Vote
      operationId: vote
      description: |
        By passing in ticket id, round and candidate name, voters can vote. Tickets id are from 1 - 999.
      parameters:
        - in: path
          name: id
          description: pass a required ticket id to vote
          required: true
          schema:
            type: number
            example: 1
        - in: path
          name: round
          description: pass a required round to vote
          required: true
          schema:
            type: string
            example: 'finalRound'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Vote'
      responses:
        '200':
          description: Vote Successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ticket'
        '400':
          description: Already Voted
  /vote/{round}:
    post:
      tags:
        - admin
      summary: Vote
      operationId: adminVote
      description: |
        By passing in round, candidate name, and ticket numbers, admin can vote. Each time admin votes, backend creates a new ticket with id such that 'admin<randomizedUUID>'.
      parameters:
        - in: path
          name: round
          description: pass a required round to vote
          required: true
          schema:
            type: string
            example: 'repechageRound'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Vote'
      responses:
        '200':
          description: Vote Successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ticket'

  /result/{round}:
    get:
      tags:
        - admin
      operationId: getResult
      description: |
        By passing in round, admin can get the result.
      parameters:
        - in: path
          name: round
          description: pass a required round to get result
          required: true
          schema:
            type: string
            example: 'semiFinalRound1'
      responses:
        '200':
          description: Get ticket result Successfully
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: string
                example:
                  Jack: 70
                  Lisa: 60
components:
  schemas:
    Vote:
      type: object
      required:
        - candidateName
        - numberOfTicket
      properties:
        candidateName:
          type: string
          example: 'Lambert'
        numberOfTicket:
          type: number
          example: 1
    Ticket:
      type: object
      required:
        - id
        - semiFinalRound1
        - semiFinalRound2
        - semiFinalRound3
        - repechageRound
        - finalRound
      properties:
        id:
          type: string
          example: '1'
        semiFinalRound1:
          type: string
          example: 'Jack'
        semiFinalRound2:
          type: string
          example: 'Rose'
        semiFinalRound3:
          type: string
          example: 'Lisa'
        repechageRound:
          type: string
          example: 'Jack'
        finalRound:
          type: string
          example: ''